import './globals.css';
import { Inter } from 'next/font/google';

import Header from './component/Header';
import { localStoreVar } from './component/responsiveComponents/LocalStore';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Hello Buddy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={localStoreVar}>
      <body className='dark:bg-slate-950 dark:text-white'>
        <Header />
        {children}
      </body>
    </html>
  );
}
