import './globals.css';
import { Inter } from 'next/font/google';

import Header from './component/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='dark'>
      <body className='dark:bg-slate-500 dark:text-white'>
        <Header />
        {children}
      </body>
    </html>
  );
}
